### ISSUE TITLE
Equally Divided Subband and Complex Spectrogram

### ISSUE THREAD

**Issue by sophia1488** [haoheliu/2021-ISMIR-MSS-Challenge-CWS-PResUNet#6]
Hi, I've read your paper and have a few questions,
1. As lower frequency contains more information, will the result be better if the subband is not equally divided?  Perhaps log-scale? (and maybe add another transformation so that they have the same shape to concatenate.)
   I'd like to try it, yet I'm not sure how the filters (`models/filters/*.mat`) are generated.
2. If I understand it correctly, the U-Net cannot see the phase information, https://github.com/haoheliu/2021-ISMIR-MSS-Challenge-CWS-PResUNet/blob/2f84db8c1455cea473eb4d72bc3779e0e37ea660/models/resunet_conv1_vocals/model.py#L195
   since only `sp` is forwarded to U-Net.  
   I've tried adding phase on other channels, so that the input to the U-Net will be (batch, channel*2, time, frequency), and the rest of the code is the same.  But the result is worse.  Do you have any thoughts on this?

Thanks a million!

**Comment by haoheliu** [comment]
@sophia1488 Hi, you made very good points! Below is my understanding.
1. Yes definitely. I divide the band equally so that it can be easily modeled by CNN and simple concatenation. If you divide the band unequally, like the filter below, you can use some projection layers to transform them into the same shape for concatenation. Alternatively, you can use other architecture instead of pure CNN to fit with subbands with different dimensions. The filter can be built using [this tool](https://www.mathworks.com/matlabcentral/fileexchange/40128-filter-bank-design).

![image](https://user-images.githubusercontent.com/42107684/145139783-b4bcf582-9c48-48d0-9b2e-07ea3b49a53e.png)

![image](https://user-images.githubusercontent.com/42107684/145139717-1f2b842f-f8a3-414b-8c63-ed5c1ce44958.png)

2. Yes. We only forward sp to U-Net because it only needs to predict phase variations instead of phase information itself. In this case, original phase information becomes less important. You can try to add phase information on each channel. But personally, I suppose original phase information is quite complex and highly nonstructural, making it hard to learn from. 

Welcome more discussions!

**Comment by sophia1488** [comment]
Hello, thanks a lot for your quick reply and detailed comments!  I'll dig into this.
Just one more question, is it okay for you to provide the command for the filter above? Since I'm not familiar with filters and I'd like to reproduce it.

Thank you 😊

**Comment by haoheliu** [comment]
@sophia1488 I've already lost the original code. But you can start with trying the following command:
```matlab
[h,f,distortion,total_aliasing]=Filter_Bank_Design([1,2,3,4],[0.1,0.2,0.3,0.4],[0.02,0.04,0.08,0.16],64,32,100,20000,[1 1],[]);
```
